-- Immutable evidence metadata for electronically signed contracts. The canonical
-- text is generated by the API; its digest makes accidental or malicious
-- alteration detectable.

alter table booking
  add column contract_sha256 text,
  add column contract_signed_ip text,
  add column contract_user_agent text;

update booking
set contract_sha256 = encode(digest(contract_text, 'sha256'), 'hex')
where contract_text is not null and contract_sha256 is null;
