import {
  Accessibility,
  AirVent,
  AlarmSmoke,
  Armchair,
  Baby,
  BadgePlus,
  Bath,
  BedDouble,
  BriefcaseBusiness,
  CableCar,
  ChevronsUpDown,
  Coffee,
  CookingPot,
  Dog,
  DoorOpen,
  Fence,
  FireExtinguisher,
  Flame,
  Flower2,
  Footprints,
  Heater,
  Home,
  KeyRound,
  Microwave,
  Mountain,
  PackageOpen,
  ParkingCircle,
  PanelTopOpen,
  PlugZap,
  Refrigerator,
  ShowerHead,
  Shirt,
  Snowflake,
  Sparkles,
  TreePine,
  Tv,
  Umbrella,
  Utensils,
  Waves,
  Warehouse,
  WashingMachine,
  Wifi,
  type LucideIcon,
} from "lucide-react";
import type { CSSProperties } from "react";
import type { AmenityIcon } from "@/lib/amenities";

const ICONS: Record<AmenityIcon, LucideIcon> = {
  wifi: Wifi,
  car: ParkingCircle,
  garage: Warehouse,
  evCharger: PlugZap,
  kitchen: Utensils,
  dishwasher: Sparkles,
  oven: CookingPot,
  microwave: Microwave,
  fridge: Refrigerator,
  washer: WashingMachine,
  dryer: AirVent,
  iron: Shirt,
  tv: Tv,
  snowflake: Snowflake,
  heating: Heater,
  fireplace: Flame,
  bath: Bath,
  shower: ShowerHead,
  bed: BedDouble,
  mountain: Mountain,
  balcony: PanelTopOpen,
  terrace: Umbrella,
  garden: TreePine,
  pool: Waves,
  hotTub: Waves,
  sauna: Heater,
  baby: Baby,
  chair: Armchair,
  pet: Dog,
  coffee: Coffee,
  workspace: BriefcaseBusiness,
  key: KeyRound,
  ski: CableCar,
  boot: Footprints,
  locker: PackageOpen,
  elevator: ChevronsUpDown,
  accessible: Accessibility,
  smokeAlarm: AlarmSmoke,
  firstAid: BadgePlus,
  extinguisher: FireExtinguisher,
  home: Home,
};

export function AmenityIconGlyph({
  icon,
  size = 22,
  color = "currentColor",
  strokeWidth = 1.8,
  className,
  style,
}: {
  icon: AmenityIcon;
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Icon = ICONS[icon] ?? Home;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} className={className} style={style} />;
}
